os: linux
dist: xenial
language: python
python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
  - "nightly"
  - "pypy3.5-6.0"
env: TOXENV=py,codecov

matrix:
  include:
    - env: TOXENV=stylecheck,docs-html
    - stage: wheel
      sudo: required
      services:
        - docker
      install:
        - pip install cibuildwheel
      script: &wheel_script
        - cibuildwheel --output-dir wheelhouse
      deploy: &wheel_deploy
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^(master|[0-9]+(.[0-9]+)*(.x)?)$
        skip_cleanup: true
        provider: s3
        access_key_id:
          secure: "zAF4qUM+MwCDt1NmMYDgHKldcQi+J2OdC/UCLfJLA/HRzIQoulIRKBcy6IEbf4IPaejwrhPtGG2LX9fIVBWsZs/3IyInf9ywSD88IdLPO0FUHcd6ebAsQSYuG2naVC9r0G6dDZzXT8vSf4Q2OxEsdsUg+NZtOmtv45jGlnuHc5Y="
        secret_access_key:
          secure: "I6OUM83O0o/N8Zvxk3vI40JDjQKniSUPPyeY5H53I+DtuUfFl0JOYHXr+XKjhM/CCGT3A2lJwugE1YOXch7fc5QRxp30Dl61ASOY3QFRp2EGNPNTBi5l9NYChPSEC96t6LzZJTSqvRmC+STrpinPW03egNKPJbBU8OKYyEyJr+M="
        bucket: pallets-wheels
        region: us-east-1
        local_dir: wheelhouse
        upload-dir: markupsafe
    - stage: wheel
      os: osx
      language: generic
      install:
        - pip2 install cibuildwheel
      script: *wheel_script
      deploy: *wheel_deploy
  allow_failures:
    - python: nightly
    - python: pypy3.5-6.0
  fast_finish: true

stages:
  - test
  - name: wheel
    if: NOT type = pull_request

install:
  - pip install tox

script:
  - tox --skip-missing-interpreters=false

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

branches:
  only:
    - master
    - /^\d+(\.\d+)*(\.x)?$/

notifications:
  email: false
